# Generated by Django 5.2.14 on 2026-06-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='No Title', max_length=255),
            preserve_default=False,
        ),
    ]
