# Generated by Django 5.2.14 on 2026-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='job',
            field=models.CharField(default='no title', max_length=255),
            preserve_default=False,
        ),
    ]
