# Generated by Django 5.2.14 on 2026-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resume_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
