# Generated by Django 6.0.6 on 2026-08-21 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان موقعیت شغلی')),
                ('company_name', models.CharField(max_length=150, verbose_name='نام شرکت')),
                ('company_initial', models.CharField(default='ش', max_length=5, verbose_name='حرف اول نام شرکت')),
                ('company_logo_color', models.CharField(default='blue', max_length=50, verbose_name='رنگ برند لوگو')),
                ('location', models.CharField(default='تهران', max_length=100, verbose_name='موقعیت مکانی')),
                ('job_type', models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('پروژه\u200cای', 'پروژه\u200cای'), ('کارآموزی', 'کارآموزی')], default='تمام وقت', max_length=50, verbose_name='نوع همکاری')),
                ('work_mode', models.CharField(choices=[('دورکاری کامل', 'دورکاری کامل'), ('امکان دورکاری (هیبریدی)', 'امکان دورکاری (هیبریدی)'), ('حضوری', 'حضوری')], default='امکان دورکاری (هیبریدی)', max_length=50, verbose_name='نحوه کار')),
                ('salary_range', models.CharField(default='توافقی', max_length=100, verbose_name='حقوق پیشنهادی')),
                ('experience_level', models.CharField(default='Senior (۳+ سال)', max_length=50, verbose_name='سطح ارشدیت')),
                ('category', models.CharField(default='برنامه\u200cنویسی و نرم\u200cافزار', max_length=100, verbose_name='دسته\u200cبندی شغلی')),
                ('skills_required', models.CharField(default='Python, Django, Docker', max_length=255, verbose_name='مهارت\u200cهای مورد نیاز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات و نیازمندی\u200cها')),
                ('benefits', models.CharField(blank=True, default='بیمه تکمیلی، پاداش، ساعت کاری منعطف، ناهار', max_length=255, verbose_name='مزایا و تسهیلات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='استخدام فوری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'موقعیت شغلی',
                'verbose_name_plural': 'موقعیت\u200cهای شغلی',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='رزومه من', max_length=150, verbose_name='عنوان رزومه')),
                ('target_job', models.CharField(blank=True, max_length=150, verbose_name='عنوان شغلی هدف')),
                ('template_name', models.CharField(choices=[('modern', 'قالب Modern (پیش\u200cفرض)'), ('minimal', 'قالب Minimal (مینیمال و تمیز)'), ('executive', 'قالب Executive (مدیران و رهبران)'), ('tech_ats', 'قالب Tech ATS (استاندارد نرم\u200cافزاری)'), ('creative', 'قالب Creative (طراحی و خلاقیت)'), ('academic', 'قالب Academic (آکادمیک و پژوهشی)')], default='modern', max_length=50, verbose_name='قالب انتخابی')),
                ('theme_color', models.CharField(choices=[('blue', 'آبی نیلی (Blue)'), ('indigo', 'نیلی عمیق (Indigo)'), ('emerald', 'زمردی (Emerald)'), ('purple', 'بنفش مدرن (Purple)'), ('slate', 'طوسی تیره (Slate)'), ('amber', 'کهربایی (Amber)'), ('rose', 'سرخابی (Rose)')], default='blue', max_length=30, verbose_name='رنگ تم')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], default='fa', max_length=10, verbose_name='زبان رزومه')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه درباره من')),
                ('skills', models.CharField(blank=True, default='Python, Django, PostgreSQL, Git', max_length=300, verbose_name='مهارت\u200cها (با کاما)')),
                ('completion_percentage', models.PositiveIntegerField(default=75, verbose_name='درصد تکمیل')),
                ('ats_score', models.PositiveIntegerField(default=82, verbose_name='امتیاز ATS')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('is_primary', models.BooleanField(default=False, verbose_name='رزومه اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزومه',
                'verbose_name_plural': 'رزومه\u200cها',
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='نام شرکت')),
                ('job_title', models.CharField(max_length=200, verbose_name='عنوان شغل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewing', 'در حال بررسی'), ('interview', 'دعوت به مصاحبه'), ('accepted', 'پیشنهاد همکاری'), ('rejected', 'عدم پذیرش')], default='pending', max_length=30, verbose_name='وضعیت درخواست')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('status_updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت کارفرما یا کاربر')),
                ('interview_time', models.CharField(blank=True, max_length=150, verbose_name='زمان مصاحبه (در صورت تعیین)')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='dashboard.joblisting', verbose_name='موقعیت شغلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='dashboard.resume', verbose_name='رزومه ارسال\u200cشده')),
            ],
            options={
                'verbose_name': 'درخواست ارسال رزومه',
                'verbose_name_plural': 'درخواست\u200cهای ارسال رزومه',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ذخیره')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='dashboard.joblisting', verbose_name='شغل ذخیره شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شغل نشان\u200cشده',
                'verbose_name_plural': 'شغل\u200cهای نشان\u200cشده',
                'unique_together': {('user', 'job')},
            },
        ),
    ]
