# Generated by Django 6.0.6 on 2026-08-21 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='تصویر پروفایل')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('headline', models.CharField(blank=True, max_length=150, verbose_name='عنوان شغلی')),
                ('bio', models.TextField(blank=True, verbose_name='درباره من')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربری',
                'verbose_name_plural': 'پروفایل\u200cهای کاربری',
            },
        ),
    ]
